name: NanoWild
author: ItsGabry
main: ItsGabry\NanoWild\Main
api: [3.0.0]
version: 1.0.0

commands:
  wild:
    description: Teleport you at random coordinates
    usage: "/wild"
    permission: wild.command

permissions:
  wild:
    children:
      wild.command:
        description: "Allows players to use wild"
        default: op